#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "aspnetcore"
name = "Asp.Net Core"
description.en = "Web api using Asp.Net core to run your .net app"
description.fr = "Une web api Asp.Net core qui vous permet de déployer votre application .net"

version = "9.0.2~ynh1"

maintainers = ["elblaa"]

[upstream]
license = "MIT"
website = "https://asp.net"
userdoc = "https://learn.microsoft.com/fr-fr/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-9.0"
code = "https://github.com/dotnet/aspnetcore"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/api"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]
    
    [resources.apt]
    extras.microsoft.repo = "deb https://packages.microsoft.com/debian/12/prod/ bookworm main"
    # extras.microsoft.key = ""
    extras.microsoft.packages = ["aspnetcore-runtime-9.0"]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/elblaa/sample_aspnetcore_ynh/releases/download/v9.0.2/dotnet-yunohost-sample-9.0.2-linux-x64.tar.gz"
        amd64.sha256 = "365b03ad3db97f65e2af056ee8c7e91a40914270def8cd990974c9200a95ab96"
        armhf.url = "https://github.com/elblaa/sample_aspnetcore_ynh/releases/download/v9.0.2/dotnet-yunohost-sample-9.0.2-linux-arm.tar.gz"
        armhf.sha256 = "c222c19da71583ba81e2a86e837f3ee37c9c3304e0870bd42fbfe8bacaffa680"
        arm64.url = "https://github.com/elblaa/sample_aspnetcore_ynh/releases/download/v9.0.2/dotnet-yunohost-sample-9.0.2-linux-arm64.tar.gz"
        arm64.sha256 = "1c3921a4f6428fe45c26c02d454560f1ae468ff65edefffc11c20a96772c22f2"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*-linux-x64.tar.gz"
        autoupdate.asset.armhf = ".*-linux-arm.tar.gz"
        autoupdate.asset.arm64 = ".*-linux-arm64.tar.gz"

    [resources.permissions]
    main.url = "/"

    [resources.install_dir]

    [resources.ports]

    
