#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "aspnetcore"
name = "Asp.Net Core"
description.en = "Web api using Asp.Net core to run your .net app"
description.fr = "Une web api Asp.Net core qui vous permet de déployer votre application .net"

version = "9.0.2~ynh1"

maintainers = ["elblaa"]

[upstream]
license = "MIT"
website = "https://asp.net"
userdoc = "https://learn.microsoft.com/fr-fr/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-9.0"
code = "https://github.com/dotnet/aspnetcore"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/api"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]
    
    [resources.apt]
    extras.microsoft.repo = "deb https://packages.microsoft.com/debian/12/prod/ bookworm main"
    extras.microsoft.key = ""
    extras.microsoft.packages = ["aspnetcore-runtime-9.0"]

    [resources.permissions]
    main.url = "/"

    [resources.install_dir]

    [resources.ports]

    
